require:
  - rubocop-factory_bot
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  SuggestExtensions: true
  TargetRubyVersion: 3.2

Metrics/MethodLength:
  CountAsOne:
    - array
    - method_call
    - hash

RSpec/ExampleLength:
  CountAsOne:
    - array
    - hash

RSpec/SpecFilePathFormat:
  CustomTransform:
    ConfigSL: configsl
