plugins:
  - rubocop-factory_bot
  - rubocop-md
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  SuggestExtensions: true
  TargetRubyVersion: 3.2
  Exclude:
    - 'out/**/*'
    - 'vendor/**/*'

Metrics/MethodLength:
  CountAsOne:
    - array
    - method_call
    - hash

RSpec/ExampleLength:
  CountAsOne:
    - array
    - hash

# Prefer greater nesting depth for better organization.
RSpec/NestedGroups:
  Max: 6

RSpec/SpecFilePathFormat:
  CustomTransform:
    ConfigSL: configsl
