name: Code Checks

on:
  push:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - run: git fetch origin main --depth=1
      - name: Set up Ruby
        # v1.316.0
        uses: ruby/setup-ruby@8e41b362d2589a22a44c1cfa214b3c83052c195b
        with:
          bundler-cache: true
      - name: RuboCop Linter
        run: bundle exec rubocop

  spec:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      code-quality: write
    strategy:
      matrix:
        ruby:
          # Run tests against all supported Rubies.
          # https://www.ruby-lang.org/en/downloads/branches/
          - "3.3"
          - "3.4"
          - "4.0"
    env:
      COVERAGE: 1

    steps:
      - uses: actions/checkout@v7
      - name: Set up Ruby
        # v1.316.0
        uses: ruby/setup-ruby@8e41b362d2589a22a44c1cfa214b3c83052c195b
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run tests
        run: bundle exec rspec
      - name: Upload coverage report
        # if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
        uses: actions/upload-code-coverage@v1
        with:
          file: coverage/coverage.xml
          language: ruby
          label: "#{matrix.ruby}"
