name: Release Gem

on:
  push:
    tags:
        - '**'

permissions:
  contents: write
  id-token: write

jobs:
  release:
    name: Release new version of ConfigSL
    runs-on: ubuntu-latest
    steps:
      - run: echo "Releasing configsl-${{ github.ref_name }}"
      - uses: actions/checkout@v7
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Push to rubygems
        uses: rubygems/release-gem@v1
